📦 Release chore(release): StarForum Client v1.0.0 pre-release2a
🔧 Fixes
fix(build): update GitHub Actions build configuration
fix(android): update Android Gradle configuration
fix(ui): update SnackBarUtil method parameters
fix(files): correct typo in ForumInfo file name
fix(cache): fix incorrect cache addresses
fix(renderer): fix content renderer issues
fix(parser): fix several parsing bugs
fix(dev): disable developer menu access in release builds
fix(post): fix incorrect reply count display on post page
fix(avatar): fix display of avatars for users without profile pictures
fix(logger): fix log record can't write to file

🔨 Refactors
refactor(ui): add initialization screen
refactor(storage): migrate database and app data storage locations
refactor(settings): add local data cache management page
refactor(cache): refactor cache management build logic
refactor(cache): refactor cache management dialog logic
refactor(settings): add “Change Base URL” page
refactor(url): update website base URL storage method to allow switching

🗑 Removals
remove(atc): delete ATC forum-specific custom features
remove(local): delete local table for i18n.

📦 Meta
chore(performance): optimize page rendering speed
chore(ui): update reply button icon on post page (@happy_tbs)

diff --git a/.github/workflows/dart.yml b/.github/workflows/dart.yml
--- a/.github/workflows/dart.yml
+++ b/.github/workflows/dart.yml
@@ -101,11 +101,32 @@ jobs:
           flutter pub get
           dart run build_runner build --delete-conflicting-outputs
 
+      - name: Setup Android signing
+        if: matrix.name == 'android'
+        run: |
+          set -e
+
+          echo "Setting up Android keystore..."
+
+          mkdir -p android/keystore
+
+          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/keystore/release.jks
+
+          cat <<EOF > android/app/keystore.properties
+          storeFile=../keystore/release.jks
+          storePassword=${{ secrets.ANDROID_STORE_PASSWORD }}
+          keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}
+          keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}
+          EOF
+
+          echo "Keystore setup complete."
+
+
       - name: Build Android APK
         if: matrix.name == 'android'
         run: |
           flutter build apk --release --target-platform android-arm64 \
-            --obfuscate --split-debug-info=./symbols
+            --obfuscate --tree-shake-icons --split-debug-info=./symbols
 
       # - name: Build Linux
       #   if: matrix.name == 'linux'
@@ -124,16 +145,20 @@ jobs:
 
       - name: Build macOS
         if: matrix.name == 'macos'
-        run: flutter build macos
+        run: flutter build macos --release --tree-shake-icons --obfuscate --split-debug-info=./symbols 
 
       - name: Compress build
         run: |
           FULL_VERSION=$(grep 'FULL_VERSION=' _build_env.config | cut -d '=' -f2)
 
-          if [ "${{ matrix.name }}" = "android" ]; then
-            mv build/app/outputs/flutter-apk/app-release.apk app-${FULL_VERSION}.apk
-            mv build/app/outputs/flutter-apk/app-release.apk ./app-release-all-${FULL_VERSION}.apk
-            mv build/app/outputs/flutter-apk/app-arm64-v8a-release.apk ./app-release-arm64-v8a-${FULL_VERSION}.apk
+           if [ "${{ matrix.name }}" = "android" ]; then
+              APK=build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
+              if [ ! -f "$APK" ]; then
+                echo "APK not found: $APK"
+                exit 1
+              fi
+              mv "$APK" app-arm64-v8a-${FULL_VERSION}.apk
+
           elif [ "${{ matrix.name }}" = "linux" ]; then
             zip -r linux-${FULL_VERSION}.zip build/linux/x64/release/bundle
           elif [ "${{ matrix.name }}" = "windows" ]; then
